# -*- mode: python ; coding: utf-8 -*-

block_cipher = None

a = Analysis(
    ['calculator.py'],
    pathex=[],
    binaries=[],
    datas=[],
    hiddenimports=[
        'yfinance',
        'curl_cffi',
        'requests',
        'pandas',
        'numpy',
        'scipy',
        'lxml',
        'bs4',
        'html5lib',
        'yfinance.core',
        'yfinance.data',
        'yfinance.utils',
        'yfinance.multi',
        'yfinance.ticker',
        'yfinance.base',
        'yfinance.constants',
        'yfinance.exceptions',
        'curl_cffi.requests',
        'curl_cffi.impersonate',
        'curl_cffi.curl',
        'curl_cffi.curl_cffi',
        'FreeSimpleGUI',
        'threading',
        'datetime',
        'time',
        'random',
        're',
        'scipy.interpolate',
        'scipy.interpolate.interp1d',
        'pandas.io.html',
        'pandas.io.html.read_html',
        'pandas.io.html._html',
        'pandas.io.html._parser',
        'requests.adapters',
        'requests.packages.urllib3',
        'requests.packages.urllib3.util',
        'requests.packages.urllib3.util.retry',
        'requests.packages.urllib3.util.timeout',
        'urllib3',
        'urllib3.util',
        'urllib3.util.retry',
        'urllib3.util.timeout',
        'urllib3.connection',
        'urllib3.connectionpool',
        'urllib3.poolmanager',
        'certifi',
        'charset_normalizer',
        'idna',
        'bs4',
        'bs4.builder',
        'bs4.element',
        'bs4.formatter',
        'lxml',
        'lxml.etree',
        'lxml.html',
        'lxml.html.clean',
        'html5lib',
        'html5lib.treebuilders',
        'html5lib.treebuilders.etree',
        'html5lib.treebuilders.etree_lxml',
        'html5lib.serializer',
        'html5lib.filters',
        'html5lib.filters.base',
        'html5lib.filters.sanitizer',
        'html5lib.filters.whitespace',
        'html5lib.filters.alphabeticalattributes',
        'html5lib.filters.optionaltags',
        'html5lib.filters.lint',
        'html5lib.filters.inject_meta_charset',
        'html5lib.filters.inputstream',
        'html5lib.filters.output',
        'html5lib.filters.sanitizer',
        'html5lib.filters.whitespace',
        'html5lib.filters.alphabeticalattributes',
        'html5lib.filters.optionaltags',
        'html5lib.filters.lint',
        'html5lib.filters.inject_meta_charset',
        'html5lib.filters.inputstream',
        'html5lib.filters.output',
        'html5lib.filters.sanitizer',
        'html5lib.filters.whitespace',
        'html5lib.filters.alphabeticalattributes',
        'html5lib.filters.optionaltags',
        'html5lib.filters.lint',
        'html5lib.filters.inject_meta_charset',
        'html5lib.filters.inputstream',
        'html5lib.filters.output',
    ],
    hookspath=[],
    hooksconfig={},
    runtime_hooks=[],
    excludes=[],
    win_no_prefer_redirects=False,
    win_private_assemblies=False,
    cipher=block_cipher,
    noarchive=False,
    collect_all_data=True,
    collect_submodules=['yfinance', 'curl_cffi', 'pandas', 'numpy', 'scipy', 'bs4', 'html5lib', 'lxml', 'requests', 'urllib3'],
    collect_data_files=True,
    collect_binaries=True,
)

pyz = PYZ(a.pure, a.zipped_data, cipher=block_cipher)

exe = EXE(
    pyz,
    a.scripts,
    a.binaries,
    a.zipfiles,
    a.datas,
    [],
    name='FiatTradeCalculator-1.0.4',
    debug=False,
    bootloader_ignore_signals=False,
    strip=False,
    upx=True,
    upx_exclude=[],
    runtime_tmpdir=None,
    console=True,
    disable_windowed_traceback=False,
    argv_emulation=False,
    target_arch=None,
    codesign_identity=None,
    entitlements_file=None,
)

# macOS app bundle
app = BUNDLE(
    exe,
    name='FiatTradeCalculator-1.0.4.app',
    icon=None,
    bundle_identifier=None,
    info_plist={
        'NSHighResolutionCapable': 'True',
        'CFBundleDisplayName': 'Fiat Trade Calculator',
        'CFBundleName': 'Fiat Trade Calculator',
        'CFBundleVersion': '1.0.4',
        'CFBundleShortVersionString': '1.0.4',
    },
)
